# Adding  profile and bashrc
[[ -e $HOME/.bashrc ]] && source $HOME/.bashrc

# The next line updates PATH for the Google Cloud SDK.
source '/usr/local/google-cloud-sdk/path.bash.inc'

# The next line enables shell command completion for gcloud.
source '/usr/local/google-cloud-sdk/completion.bash.inc'
