# Adding  profile and bashrc
[[ -e $HOME/.bashrc ]] && source $HOME/.bashrc

# The next line updates PATH for the Google Cloud SDK.
if [ -f '/Users/sgm/src/google-cloud-sdk/path.bash.inc' ]; then source '/Users/sgm/src/google-cloud-sdk/path.bash.inc'; fi

# The next line enables shell command completion for gcloud.
if [ -f '/Users/sgm/src/google-cloud-sdk/completion.bash.inc' ]; then source '/Users/sgm/src/google-cloud-sdk/completion.bash.inc'; fi

# Pyenv
if which pyenv-virtualenv-init > /dev/null; then eval "$(pyenv virtualenv-init -)"; fi
