alias emacs='emacs -nw'
if [ -x /usr/bin/dircolors ]; then
    eval "`dircolors -b`"
    alias dir='dir --color=auto'
    alias vdir='vdir --color=auto'
    alias ls='ls --color=auto'
    alias l='ls -l'
    alias ll='ls -la'
    alias lr='ls -lrth'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi
