" --- Common
syntax enable
filetype plugin indent on


set nocompatible
set background=dark
set encoding=utf8
set showcmd
set showmode
set backspace=indent,eol,start
set backupdir=~/.vimswp
set directory=~/.vimswp

set wildmode=list:longest
set history=1000
set scrolloff=3
set hlsearch
set incsearch
set hidden
set wildmenu
set ignorecase
set smartcase
set title

" When doing search and replace, add g flag by default"
set gdefault
set undolevels=1000

"Enable spell checking
"set spell
"set spelllang=en

runtime macros/matchit.vim

" --- Key mapping
imap jk <ESC>
map 9 :bp<CR>
nnoremap <space> za
vnoremap <space> zf
nnoremap <f12> :e $MYVIMRC<CR>
map      <f2> :NERDTreeToggle <CR>

" --- Plugins
call pathogen#infect()
autocmd vimenter * if !argc() | NERDTree | endif
autocmd BufNewFile,BufRead *.yaml,*.yml silent

" --- Disabling keys
nnoremap <up>   <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" --- Gvim
if has("gui_running")
   highlight Normal     guifg=grey guibg=black
   colorschem badwolf
   set guioptions-=m 
   set guioptions-=T
   set guioptions-=r

   "Disable NERDTree arrows
   "let g:NERDTreeDirArrows=0
   
   if has("gui_gtk2")
	   "set guifont=Luxi\ Mono\ 12
		   set guifont=Lucida\ Console\ 11
   elseif has("x11")
	   " Also for GTK 1
	   set guifont=*-lucidatypewriter-medium-r-normal-*-*-180-*-*-m-*-*
   elseif has("gui_win32")
	   set guifont=Luxi_Mono:h12:cANSI
   endif

endif
