" --- Common
syntax enable
filetype plugin indent on


set nocompatible
set background=dark
set encoding=utf8
set showcmd
set showmode
set backspace=indent,eol,start
set backupdir=~/.vimswp
set directory=~/.vimswp

set wildmode=list:longest
set history=1000
set undolevels=1000
set scrolloff=3
set hlsearch
set incsearch
set hidden
set wildmenu
set ignorecase
set smartcase
set title

" When doing search and replace, add g flag by default"
set gdefault

runtime macros/matchit.vim

" --- Key mapping
imap jk <ESC>
map 9 :bp<CR>
nnoremap <space> za
vnoremap <space> zf
nnoremap <f12> :e $MYVIMRC<CR>
map      <f2> :NERDTreeToggle <CR>

" --- Plugins
call pathogen#infect()
autocmd vimenter * if !argc() | NERDTree | endif
autocmd BufNewFile,BufRead *.yaml,*.yml silent

" --- Save file using update, only if there are changes, conflics
" --- if you want to send Vim to background.

"noremap <C-Z> :update<CR>
vnoremap <C-Z> :update<CR>
inoremap <C-Z> :update<CR>

" --- Closing faster
let mapleader=","
noremap <Leader>e :quit<CR>
noremap <Leader>E :qa!<CR>


" --- Tab navigating
map <Leader>n 	<esc>:tabprevious<CR>
map <Leader>m 	<esc>:tabnext<CR>
map <Leader>q	<esc>:tabclose<CR>
map <Leader>c	<esc>:tabnew<CR>


" --- Moving code blocks
vnoremap < <gv
vnoremap > >gv

" --- Sort in vistual mode
map <Leader>s :sort<CR>

" --- Highlight column more 80 chars
call matchadd('ColorColumn', '\%81v', 100)
highlight ColorColumn ctermbg=magenta
set colorcolumn=81

" --- Visual split of line according column=80
vmap Q 	gq
vmap Q  gqap


" --- Autoreload vimrc
autocmd! bufwritepost .vimrc source %


" --- Disabling keys
nnoremap <up>   <nop>
nnoremap <down> <nop>
nnoremap <left> <nop>
nnoremap <right> <nop>
nnoremap <C-e> 3<C-e>
nnoremap <C-y> 3<C-y>

" Normal mode
nnoremap <C-j> :m .+1<CR>==
nnoremap <C-k> :m .-2<CR>==

" Insert mode
"inoremap <C-j> <ESC>:m .+1<CR>==gi
"inoremap <C-k> <ESC>:m .-2<CR>==gi

" Visual mode
vnoremap <C-j> :m '>+1<CR>gv=gv
vnoremap <C-k> :m '<-2<CR>gv=gv


" --- Gvim
if has("gui_running")
   highlight Normal     guifg=grey guibg=black
   colorschem badwolf
   set guioptions-=m 
   set guioptions-=T
   set guioptions-=r

   "Disable NERDTree arrows
   "let g:NERDTreeDirArrows=0
   
   if has("gui_gtk2")
	   "set guifont=Luxi\ Mono\ 12
		   set guifont=Lucida\ Console\ 11
   elseif has("x11")
	   " Also for GTK 1
	   set guifont=*-lucidatypewriter-medium-r-normal-*-*-180-*-*-m-*-*
   elseif has("gui_win32")
	   set guifont=Luxi_Mono:h12:cANSI
   endif

endif
